version: "3"

services:
  server:
    image: okhanyu/minichat:latest
    container_name: minichat
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./config.yaml:/app/config.yaml"
    environment:
      - TEMPLATE_NAME=bulma
